language: python
branches:
  only:
    - dev
    - master
install:
  - pip install -U tox
script:
  - tox
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37,up_analysis
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
