language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
branches:
  only:
    - dev
    - master
install:
  - pip install -U pip
  - pip install -U tox
cache:
  directories:
    - /home/travis/.cache/pip
    - /home/travis/.cache/pipenv
script:
  - tox
