language: python
branches:
  only:
    - dev
    - master
install:
  - pip install -U tox
script:
  - tox
matrix:
  include:
    - python: 3.8
      env: TOXENV=py38,up_analysis
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=py36
